import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import Template from "@/components/Template";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Template>{children}</Template>
        <footer className="w-screen bottom-0 p-4 left-0 fixed bg-[#E7E7E7]">
          <p className="text-sm mx-auto w-fit text-zinc-500 font-medium">
            We do not store your personal data. We take your privacy very
            serious.
          </p>
        </footer>
      </body>
    </html>
  );
}
